services:
  - type: web
    name: researchai-backend
    runtime: node
    rootDir: backend
    buildCommand: npm install
    startCommand: npm run start
    envVars:
      - key: PORT
        value: 4001
      - key: DATABASE_URL
        sync: false
      - key: JWT_ACCESS_SECRET
        sync: false
      - key: JWT_REFRESH_SECRET
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: GEMINI_MODEL
        value: gemini-3-flash-preview
      - key: GEMINI_EMBEDDING_MODEL
        value: gemini-embedding-001
